package com.LOLdaojucheng.dao;


import com.LOLdaojucheng.pojo.Product;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;
import java.util.Set;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Product record);

    /***
     * 更改商品状态
     * @param product
     * @return
     */
    int set_sale_status(Product product);
    /***
     * 按照 productID productName查询
     */
    List<Product> search(@Param("productName") String productName,
                         @Param("productId") Integer productId);

    /**
     * 前台—搜索商品
     */
    List findProduct(@Param("set") Set<Integer> set,
                     @Param("keyword") String keyword
                     );
    /***
     * 前台搜索热门商品
     */
    List<Product> selectHotProduct(@Param("code") Integer code);

    /***
     * 前台搜索打折商品
     */
    List<Product> selectRebateProduct(@Param("code") Integer code);

    /***
     * 前台搜索热门排行
     */
    List<Product> selectHot(@Param("code") Integer code);

    /***
     * 前台模糊查询
     */
    List<Product> mohuchaxun(@Param("word") String word);

    /***
     * 查询手办
     */
    List<Product> shouban(@Param("code1") Integer code1,
                          @Param("code2") Integer code2,
                          @Param("code3") Integer code3);

    /***
     * 更改商品数量
     */
    int updateStock(@Param("productId")Integer productId,@Param("stock")Integer stock);
    int updateDetails(@Param("productId")Integer productId,@Param("details")String details);
    /***
     * 更改商品状态，商品折扣以及商品价格
     */
    int updateProduct(@Param("productId") Integer productId,
                      @Param("rebate") Integer rebate,
                      @Param("price")BigDecimal price,
                      @Param("status")Integer status);
}