package com.LOLdaojucheng.dao;

import com.LOLdaojucheng.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserInfo record);
    /**
     * 检查用户名是否存在
     * */
    int checkUser(String username);
    /**
     * 检查邮箱是否存在
     * */
    int checkEmail(String Email);
    /**
     * 根据用户名和密码查找用户信息
     * */
    UserInfo selectUserByUsernameAndPassword(@Param("username") String username,
                                             @Param("password") String password);
    /**
     * 根据用户名查找密保问题
     * */
    String selectQuestionByUsername(String  username);

    /**
     * 根据用户名、问题以及答案查询答案是否正确
     * */
    int selectQueryByUsernameAndQuestionAndAnswer(@Param("username") String username,
                                                  @Param("question") String question,
                                                  @Param("answer") String answer);
    /**
     * 根据用户名以及forgettoken修改密码
     * */
    int updatePasswordByUsernameAndForgettoken(@Param("username") String username,
                                               @Param("password") String password);
    /**
     * 登录状态更改用户信息
     * */
    int update_information(UserInfo userInfo);
    /**
     * 根据用户id查询用户信息
     * */
    UserInfo getInformationById(int id);

    /***
     * 更新用户的token信息
     */
    int updateTokenByUserId(@Param("userId") Integer userId,
                            @Param("token") String token);
    /***
     * 根据token查询用户信息
     */
    UserInfo findUserInfoByToken(String token);

    /***
     * 更改用户状态
     */
    int updateRole(@Param("userId") Integer userId,
                   @Param("role")Integer role);

}